name: 'Validate PR'
on:
  pull_request:
    branches: [main]

jobs:
  ci:
    name: 'Validate PR'
    runs-on: 'ubuntu-latest'
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.target_commitish }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: 'yarn'
          scope: '@mtnkente'
          registry-url: https://npm.pkg.github.com/
          always-auth: true

      - name: Install CLI dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Check format
        run: yarn run format:check

      - name: Check Linting
        run: yarn run lint:check

      - name: Run unit testing
        run: yarn run test

      - name: Build artifacts
        run: yarn run build
